### ISSUE TITLE
Improve the project organization

### ISSUE THREAD

**Issue by gerodriguezUAD** [OswaldoPeM/Programacion-2-Oswaldo-Perez-Macias#1]
Improve the project organization

Rename the directories of each practice using the format: Practice # - *description*
For example:
Practice 1 - BubbleSort y SelectionSort
Practice 2 - QuickSort
Practice 3 - Sort Comparison
Practice 4 - Inheritance and friendship

**Comment by OswaldoPeM** [comment]
Fixed on prev and master
